# Generación de Reporte de Resultados

> **Antes de comenzar**
>
> Este laboratorio está diseñado para ejecutarse en **Google Colab**.
>
> Una vez abierto en Google Colab, ejecute la primera celda para clonar el repositorio del curso y acceder a los conjuntos de datos utilizados en este laboratorio.

In [39]:
!git clone https://github.com/urendacdenisse-hub/ingenieria-de-datos.git

fatal: destination path 'ingenieria-de-datos' already exists and is not an empty directory.

In [40]:
%cd ingenieria-de-datos

/content/ingenieria-de-datos/ingenieria-de-datos

## Introducción

En esta actividad aplicarás nuevamente las etapas del ciclo de vida de los datos utilizando un conjunto de datos proveniente de una **encuesta**.

Esta vez deberás seleccionar tu propio conjunto de datos y recorrer el mismo proceso visto en el laboratorio, desde la ingesta hasta la generación de un reporte.


## Objetivo

Al finalizar esta actividad serás capaz de:

- Aplicar las principales etapas del ciclo de vida de los datos a un nuevo conjunto de datos.
- Seleccionar y analizar variables de interés.
- Comunicar los resultados mediante una gráfica y un reporte.

## Instrucciones

Durante la actividad deberás:

1. Buscar y seleccionar en [**Kaggle**](https://www.kaggle.com/datasets?search=survey) un conjunto de datos proveniente de una encuesta:
   - Debe contener respuestas individuales.
   - Debe incluir varias preguntas o variables.
   - No debe contener **información personal identificable**.

2. Descargar el conjunto de datos seleccionado desde **Kaggle** en formato CSV.

3. Cargar el archivo CSV en Google Colab.

4. Guardar una copia del conjunto de datos original en formato **CSV**.

5. Inspeccionar el contenido del conjunto de datos identificando:
   - número de registros,
   - tipos de datos,
   - valores faltantes.

6. Limpiar y preparar el conjunto de datos para el análisis:
   - tratar los valores faltantes cuando sea necesario,
   - corregir tipos de datos cuando sea necesario,
   - identificar y corregir posibles inconsistencias.

7. Plantear una **pregunta de análisis** que pueda responderse utilizando los datos de la encuesta.

8. Seleccionar las variables necesarias para responder la pregunta planteada.

9. Realizar las operaciones o estadísticas necesarias para responder la pregunta.

10.  Generar una **gráfica** que permita comunicar los resultados y guardarla como imagen.

11. Elaborar un reporte en **Microsoft Word** que incluya:
    - nombre de la actividad,
    - tu nombre,
    - nombre y enlace del dataset seleccionado,
    - pregunta de análisis,
    - gráfica generada,
    - breve interpretación de los resultados (entre 5 y 10 líneas).

12. Exportar el documento a formato **PDF**.

13. Una vez confirmado que la imagen fue incorporada al reporte, ejecutar la última celda del notebook para eliminar el archivo PNG generado.
---

Aquí comienza la actividad. ¿Listo?

In [41]:
# =================================================
# 🚫 NO MODIFICAR ESTA CELDA... O SE CREASHEA
# Configura todo lo necesario para comenzar
# =================================================

import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent.parent))

CARPETA_SALIDA = Path("ingenieria-de-datos/datos/salida")
CARPETA_SALIDA.mkdir(parents=True, exist_ok=True)

from recursos.codigo.visualizacion import visualizar_resultados

In [45]:
# ==========================================================
# 3. Carga de datos
#    Cargar el archivo CSV descargado desde Kaggle
#    en un DataFrame llamado `datos`
# ==========================================================

import pandas as pd

ruta = "/content/ingenieria-de-datos/datos/entrada/student_data.csv"
datos = pd.read_csv(ruta)
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    384 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    376 non-null    float64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: float64(1), int64(15), object(17)
memory usage: 102.0+ KB

In [48]:
# ==========================================================
# 4. Almacenamiento de datos
#    Guardar una copia de los datos originales en formato CSV
#    dentro de la carpeta de salida
# ==========================================================

ruta = CARPETA_SALIDA / "/content/ingenieria-de-datos/datos/salida/student_data_copia.csv"

datos.to_csv(ruta)
# El método .to_scv exporta un archivo a una ruta que nosotros le digamos; fungiendo como una copia de seguridad antes de empezar a trabajar, dandonos otro archivo.

In [54]:
# ==========================================================
# 5. Inspección de datos
#    Examinar el conjunto de datos e identificar:
#    - número de registros
#    - tipos de datos
#    - valores faltantes
# ==========================================================
datos.shape[0] # Devuelve la cantidad de filas

395

In [55]:
datos.dtypes # Devuelve los tipos de datos

school         object
sex            object
age             int64
address        object
famsize        object
Pstatus        object
Medu            int64
Fedu            int64
Mjob           object
Fjob           object
reason         object
guardian       object
traveltime      int64
studytime       int64
failures        int64
schoolsup      object
famsup         object
paid           object
activities     object
nursery        object
higher         object
internet       object
romantic       object
famrel          int64
freetime        int64
goout           int64
Dalc            int64
Walc            int64
health          int64
absences      float64
G1              int64
G2              int64
G3              int64
dtype: object

In [57]:
datos.isnull().sum() #Muestra los vacíos

school         0
sex            0
age            0
address        0
famsize        0
Pstatus        0
Medu           0
Fedu           0
Mjob           0
Fjob           0
reason         0
guardian       0
traveltime     0
studytime      0
failures       0
schoolsup      0
famsup         0
paid           0
activities     0
nursery        0
higher         0
internet      11
romantic       0
famrel         0
freetime       0
goout          0
Dalc           0
Walc           0
health         0
absences      19
G1             0
G2             0
G3             0
dtype: int64

# Las columnas que tienen vacíos

In [86]:
datos[datos["internet"].isnull()] # Trae los registros que tienen vaciós en la columna internet

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
74,GP,female,16,U,GT3,T,3,3,other,services,...,4,3,3,2,4,5,54.0,11,12,11
93,GP,female,16,U,GT3,T,4,2,teacher,services,...,5,3,3,1,1,1,0.0,11,10,10
167,GP,Female,16,U,GT3,T,4,2,health,services,...,4,2,3,1,1,3,0.0,14,15,16
184,GP,Female,16,U,GT3,T,3,2,other,other,...,1,2,2,1,2,1,14.0,12,13,12
191,GP,F,17,U,GT3,T,1,1,at_home,services,...,5,3,3,1,1,3,0.0,8,8,9
211,GP,male,17,U,LE3,T,4,4,services,other,...,5,3,5,4,5,3,13.0,12,12,13
291,GP,F,17,U,GT3,T,4,3,health,services,...,4,2,2,1,2,3,0.0,15,15,15
309,GP,Female,19,U,LE3,T,1,1,at_home,other,...,4,4,3,1,3,3,18.0,12,10,10
318,GP,Female,17,R,GT3,T,3,4,at_home,services,...,4,3,4,2,5,5,0.0,11,11,10
344,GP,Female,18,U,GT3,T,2,3,at_home,other,...,4,3,3,1,2,3,4.0,11,10,10
345,GP,female,18,U,GT3,T,3,2,at_hOme,services,...,5,4,3,2,3,1,7.0,13,13,14

In [87]:
datos[datos["absences"].isnull()]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
11,GP,female,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,NaN,10,12,12
47,GP,male,16,U,GT3,T,4,3,health,services,...,4,2,2,1,1,2,NaN,19,19,20
89,GP,Male,16,U,LE3,A,4,4,teacher,health,...,4,1,3,3,5,5,NaN,8,6,7
96,GP,M,16,R,GT3,T,4,3,services,other,...,3,3,3,1,1,4,NaN,11,15,15
110,GP,male,15,U,LE3,A,4,4,teacher,teacher,...,5,5,3,1,1,4,NaN,18,19,19
157,GP,F,18,R,GT3,T,1,1,at_home,other,...,5,2,5,1,5,4,NaN,9,8,10
170,GP,M,16,U,GT3,T,3,4,other,other,...,3,4,5,2,4,2,NaN,6,5,0
173,GP,F,16,U,GT3,T,1,3,at_home,services,...,4,3,5,1,1,3,NaN,8,7,0
179,GP,Male,17,U,GT3,T,4,3,servics,other,...,5,2,3,1,1,2,NaN,10,10,11
183,GP,F,17,U,LE3,T,3,3,other,other,...,5,3,3,2,3,1,NaN,9,9,8
212,GP,Female,16,U,GT3,A,2,2,other,other,...,3,3,4,1,1,4,NaN,12,13,14
233,GP,Male,16,U,GT3,T,4,4,health,other,...,4,2,4,2,4,1,NaN,14,13,13
236,GP,Male,17,U,LE3,T,2,2,other,other,...,4,4,2,5,5,4,NaN,14,13,13
241,GP,Male,17,R,LE3,A,4,4,teacher,other,...,3,3,3,2,3,4,NaN,10,11,12
267,GP,Female,18,R,GT3,T,4,4,teacher,other,...,4,3,4,2,2,4,NaN,12,10,11
288,GP,M,18,U,GT3,T,2,1,services,services,...,4,2,4,1,3,2,NaN,15,14,14
325,GP,M,18,U,GT3,T,4,4,other,other,...,4,3,3,2,2,3,NaN,9,12,11
341,GP,male,18,U,GT3,T,4,4,teacher,services,...,4,3,3,2,2,2,NaN,10,10,0
356,MS,Female,17,R,GT3,T,4,4,teacher,services,...,4,3,3,1,2,5,NaN,12,13,13

In [105]:
datos_int_abs = datos[ datos["internet"].isnull() | datos["absences"].isnull() ]
datos_int_abs[["internet", "absences"]]

    internet  absences
11       yes       NaN
47       yes       NaN
74       NaN      54.0
89        no       NaN
93       NaN       0.0
96       yes       NaN
110      yes       NaN
157       no       NaN
167      NaN       0.0
170      yes       NaN
173      yes       NaN
179      yes       NaN
183      yes       NaN
184      NaN      14.0
191      NaN       0.0
211      NaN      13.0
212      yes       NaN
233      yes       NaN
236      yes       NaN
241      yes       NaN
267      yes       NaN
288      yes       NaN
291      NaN       0.0
309      NaN      18.0
318      NaN       0.0
325      yes       NaN
341      yes       NaN
344      NaN       4.0
345      NaN       7.0
356      yes       NaN

In [ ]:
# ==========================================================
# 6. Limpieza de datos
#    Preparar los datos para el análisis:
#    - tratar valores faltantes
#    - corregir tipos de datos
#    - corregir inconsistencias cuando sea necesario
# ==========================================================

# datos_limpios = datos.copy()
# datos_limpios...

In [ ]:
# ==========================================================
# 8. Selección de datos
#    Seleccionar las variables necesarias para responder
#    la pregunta de análisis
# ==========================================================

columnas = [
    "<columna 1>",
    "<columna 2>",
    "<columna 3>",
    "<columna 4>"
]

# datos_analisis = datos_limpios[...]

In [ ]:
# ==========================================================
# 9. Análisis de datos
#    Realizar las operaciones o estadísticas necesarias
#    para responder la pregunta planteada
# ==========================================================

# datos_analisis.<metodo>(...)

In [ ]:
# ==========================================================
# 10. Visualización de resultados
#    Generar una gráfica que permita comunicar los resultados
#    del análisis y guardarla como imagen
# ==========================================================

# Puedes hacer tu propia grafica o intentar usar la funcion
# ya creada, solo asegurate de que los datos que ingresas tenga
# variables categoricas (tipo texto).

# figura = visualizar_resultados(datos_analisis)


ruta = CARPETA_SALIDA / "<nombre de imagen>.png"

In [ ]:
# ==========================================
#    Crear ruta de imagen
# ==========================================

ruta = CARPETA_SALIDA / "<nombre de imagen>.png"

# ==========================================
#    Guardar los resultados para uso posterior
# ==========================================

#figura.savefig(
#    fname=ruta,
#    dpi=300,
#    bbox_inches="tight"
#)

print(f"Guardado en: {ruta.resolve()}")

In [ ]:
# =====================================================
# 13. Conservacion y eliminacion de datos
#    Eliminar gráfico
#    ⚠️ Corre una vez realizado el reporte final.
# =====================================================

if ruta.exists():
    ruta.unlink()
    print("🗑️ La imagen fue eliminada.")
else:
    print("⚠️ La imagen ya no existe.")